### ISSUE TITLE
Sidebar has scrollbars for headings with code fomatting

### ISSUE THREAD

**Issue by jkloosterman** [eecs485staff/primer-spec#100]
**Describe the bug**
If there are headings that include code formatting, those headings are shown with individual vertical scrollbars in the sidebar

**To Reproduce**
1. Go to https://eecs485staff.github.io/p2-insta485-serverside/
2. Observe that there are scrollbars in the sidebar

**Expected behavior**
There are no scrollbars for individual headings in the sidebar.

**Screenshots**
![image](https://user-images.githubusercontent.com/3603526/103662310-c7e1de80-4f3d-11eb-8701-e4cd2e4b9b1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 87.0.4280.88

**Comment by awdeorio** [comment]
I think this is expected behavior.  At least, that's what I had in mind when I made those headings.  If you think there's a more clear way to present the spec and/or sidebar in that project let me know.  I think this is EECS 485 P2.

**Comment by jkloosterman** [comment]
I'm referring to the tiny scrollbars for each item, like "/accounts/logout/". The scrollbar only scrolls a pixel or two.

**Comment by seshrs** [comment]
Thanks for reporting @jkloosterman! The vertical scrollbars definitely look jarring... I think the fix could be to simply never show vertical scrollbars. (It's probably okay if content gets cut vertically, I expect this would only happen if using extra tall characters like those in some non-Latin scripts.)
