### ISSUE TITLE
Change default branch to master

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#109]
With the changes in benbalter/jekyll-remote-theme#87, Jekyll Remote Theme will use the default repo branch if a ref is not specified in `_config.yml`. This won't break Primer Spec rendering, but it means that Primer Spec users will be building off of the `develop` branch instead of `master` by default!

(Note that the new version of Jekyll Remote Theme hasn't been released yet, but when it is adopted by GitHub Pages, this new behavior will kick in.)

To maintain the current process where `master` is only updated once every few months, we should either:
1. Make `master` the default branch for this repo
2. Update the setup instructions so that all users specify using the `master` ref instead of providing no ref.

I'm leaning towards option 2. However, that requires communicating with every existing user of Primer Spec to update their `_config.yml` file...

**Comment by awdeorio** [comment]
This is frustrating!  Ideally, `develop` would be the default for developers, e.g., when they make a pull request, it would be against `develop`.  Ideally, `master` would be the default for end users, e.g., when they use the remote theme.

Users are going to copy/paste `_config.yml` anyways, so I think user error is less likely to be a problem going with option 1.

**Comment by seshrs** [comment]
Yeah, I didn’t think of this when the changes to jekyll-remote-theme were first proposed 😓

> Users are going to copy/paste _config.yml anyways, so I think user error is less likely to be a problem going with option 1.

I was hoping that if users blindly copy/paste from the setup docs, we could modify the default `_config.yml` to specifically build from `master`. But you’re right that it’s not exactly backwards compatible 😞 

So yeah, maybe let’s go with option 1 and also create a GitHub Actions workflow to automatically close PRs targeting the `master` branch.

**Comment by awdeorio** [comment]
I think my previous comment wasn't very clear.  I was originally advocating for option 2!  Now that I think about it, I think that neither way is perfect.  On balance, I would side with making things easier for the users rather than the developers.  That's Option 1.  That's my final opinion!

I wonder if it's possible to get the same behavior as GitHub pages, which provides the option to publish from *from the master branch*.  It sounds like maybe not, but that would be the ideal behavior.

**Comment by seshrs** [comment]
I agree, let’s do option 1 😃

> I wonder if it's possible to get the same behavior as GitHub pages, which provides the option to publish from from the master branch. It sounds like maybe not, but that would be the ideal behavior.

Hmm, that would be a nice feature for jekyll-remote-theme! I can look into opening a PR, but it doesn’t really match existing GitHub/Jekyll paradigms. (Even with GitHub actions, users are expected to provide a ref, otherwise the default branch is used.)
