### ISSUE TITLE
Broken URL in Preview

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#125]
**Describe the bug**
Links from a preview to another page that is part of the same preview appear to be broken.

**To Reproduce**
1. Navigate to the [preview](https://preview.seshrs.ml/previews/eecs280staff/p1-stats/199/) for this [PR](https://github.com/eecs280staff/p1-stats/pull/199)
2. Using the sidebar, navigate to the "Mega Setup Tutorial"
2. Scroll down and find an internal link to another page within the same preview, say, the "Visual debugger" section.  If you click the link of "VS Code Tutorial", the href is https://preview.seshrs.ml/setup_vscode.html

**Expected behavior**
I think https://preview.seshrs.ml/setup_vscode.html should be https://preview.seshrs.ml/previews/eecs280staff/p1-stats/199/setup_vscode.html

**Additional context**

**Comment by seshrs** [comment]
Ah whoops! I should have redirected instead of simply serving the expected file. I've fixed Primer Spec Preview in https://github.com/seshrs/primer-spec-preview/commit/a97e377bc01c5544e1458f090df50508ad65fe64, and the change is live now 😄

**Comment by awdeorio** [comment]
Thanks @seshrs !
