### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#126]
To follow the pattern of EECS 485 repos (and [the broader movement across GitHub](https://github.com/github/renaming)), let’s rename the `master` branch to `main`. 

- [x] Verify Jekyll Remote Theme support
  - Supported in [v0.4.3](https://github.com/benbalter/jekyll-remote-theme/releases/tag/v0.4.3). This version is also [used by GitHub Pages](https://pages.github.com/versions/).
- [x] Freeze and release existing `develop` branch.
- [x] Update GitHub Actions references to `master` branch.
- [x] Also check other repo’s preview workflows. 
  - Verified EECS 280, EECS 485
- [x] Update README and other references in docs.
- [x] Create new `main` branch on top of existing `master` branch.
- [x] Make `main` the default branch (with `master` as shadow. 
- [ ] Email course staff for all known users, ensure that their `_config.yml` files are updated to *not* specify `master` ref.
- [ ] Delete `master` branch. Bump **major** version.
- [ ] Remove temporary code in workflows and scripts that kept `master` synced with `main`.

**Comment by seshrs** [comment]
I just realized that this is a bit trickier since some courses have specified the remote theme in their `_config.yml` as `eecs485staff/primer-spec@master`. It will probably take some time to ensure that course websites have been correctly updated.

**Comment by awdeorio** [comment]
>  Update GitHub Actions references to `master` branch. Also check other repo’s preview workflows.

I forgot about this one.  Thanks for the reminder!

**Comment by seshrs** [comment]
I think it’s ok to maintain both a `master` and a `main` branch, and to use GH Actions to keep them in sync. (We can drop the follow-up items from my original list.)
