### ISSUE TITLE
Highlight line in code block

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#130]
It would be nice if it were possible for the spec to _highlight_ a particular line (or lines) in a code block for emphasis. 

Something similar to GitHub highlighting a line when you click the line number in a file. 

This is tricky because the Jekyll default code formatter (Rouge) doesn’t support it, and neither do traditional markdown code blocks.

**Comment by awdeorio** [comment]
One example of where such a feature would be useful is the EECS 485 [Threads and Sockets in Python](https://eecs485staff.github.io/p4-mapreduce/threads-sockets.html) tutorial, which contains several long examples.  It would be nice to explain certain lines from within those examples.  Moreover, it would be cool if you could highlight different lines in different colors.  Then, use those colors in the text to explain.

**Comment by seshrs** [comment]
Closed by #131.
