### ISSUE TITLE
Syntax highlights for console block with multline output

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#149]
**Describe the bug**
A console block with a command that produces multiple lines of output should color the output differently from the command.  It looks like only the first line of output is recognized as output.

**To Reproduce**
This is a `console` block
```
$ pgrep -lf mapreduce-  # macOS
77760 /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/awdeorio/src/eecs485/p4-mapreduce/env/bin/mapreduce-manager 6000 5999
77811 /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/awdeorio/src/eecs485/p4-mapreduce/env/bin/mapreduce-worker 6001 6000 5999
77893 /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python /Users/awdeorio/src/eecs485/p4-mapreduce/env/bin/mapreduce-worker 6002 6000 5999
```

**Expected behavior**
All lines of output should appear grey, just like the first line.

**Screenshots**
Here's an example from EECS 485 P4 https://eecs485staff.github.io/p4-mapreduce/example.html#start-manager

<img width="493" alt="Screen Shot 2022-02-04 at 2 53 23 PM" src="https://user-images.githubusercontent.com/7503005/152594520-d0767679-e2df-42a2-b34b-28dbd3e42af9.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Brave
 - Version [e.g. 22] 98 or something

**Additional context**

**Comment by seshrs** [comment]
Thanks for reporting @awdeorio! Turns out that I accidentally introduced this bug while designing the *enhanced* code blocks. I have a fix, but I'll need to test and clean it a bit over the weekend.
