### ISSUE TITLE
Enhanced code block option to disable line numbers

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#159]
**Is your feature request related to a problem? Please describe.**

In rare cases, the line numbers on enhanced code blocks can be confusing.  From the EECS 485 [P5 spec](https://eecs485staff.github.io/p5-search-engine/#job-0), there's an example where the output of a code block is a number, which is easily confused with the line number.

<img width="606" alt="p5-confusing-number" src="https://user-images.githubusercontent.com/7503005/157988212-3d2e3a35-aa3a-4397-bfff-0d2aca9b6180.png">

**Describe the solution you'd like**

An option to disable line numbers on an enhanced code block would be nice.

**Describe alternatives you've considered**

I used `{: data-variant="legacy" }`, but the downside is an inconsistent look and feel next to the other code  blocks.

**Comment by seshrs** [comment]
Thanks for reporting! I think it's quite reasonable to want to turn line-numbers off. I *think* I can provide an option to simply *not* display line numbers, maybe an option like `data-variant="no-line-numbers"`.

Do you need this for this semester? If it can wait for next semester, I'd prefer to address it in a couple of weeks once my personal life settles down a bit :)

**Comment by awdeorio** [comment]
This is totally low priority!

**Comment by seshrs** [comment]
Reminder that #165 will be included in the SP/SU 22 release (currently aiming for April 30). I'm going to keep this issue open for now, and will close it after v1.7.0 has been published.

**Comment by seshrs** [comment]
@awdeorio [I just released v1.7.0](https://github.com/eecs485staff/primer-spec/releases/tag/v1.7.0%2Bss22)! I'm going to close this issue, but please follow up if you're running into issues. Thanks!
