### ISSUE TITLE
Headers with inline italics don't show up properly in the TOC.

### ISSUE THREAD

**Issue by marcus-darden** [eecs485staff/primer-spec#160]
**Describe the bug**
There was a top-level header (single \#) that had italics, and everything from the beginning of the italics to the end of the line was removed from the link in the Table of Contents.

**To Reproduce**
Include the following in a markdown file and build with the primer-spec:
```
# This is my _"Title"_
```

**Expected behavior**
Item renders well in the document body, but the TOC in the sidebar should include "Title" (preferably italicized).

**Comment by seshrs** [comment]
Thanks for reporting, that seems like a really bad bug! Is this issue currently visible on a live spec? (Just to help me prioritize — if this can wait a bit, I'd prefer to explore and address this in a couple of weeks 😅)

**Comment by seshrs** [comment]
@marcus-darden I plan to release the fix before the SP/SU 22 semester. Does that work for you? (Let me know if you need the fix sooner.)

Closing this issue (but feel free to continue to comment).
