### ISSUE TITLE
no-line-numbers doesn't work if useLegacyCodeBlocks is true?

### ISSUE THREAD

**Issue by sugihjamin** [eecs485staff/primer-spec#168]
**Describe the bug**
I have a site wide `userLegacyCodeBlock: true`
On my page, I have:

```console
server$ sudo apt update
server$ sudo apt install python3-pip python3-dev python3-venv libpq-dev postgresql postgresql-contrib nginx curl
server$ sudo ln -s /usr/bin/python3 /usr/bin/python
```
{: data-variant="no-line-numbers" data-highlight="3" }

Data highlight shows up but the code block still shows up with line numbers.

**To Reproduce**
1. Go to https://eecs441.eecs.umich.edu/asns/lab0-chatter-backend#installing-packages
3. Scroll down to first code block
4. See error: code block shows up with line numbers

**Expected behavior**
Code block doesn't have line numbers

**Screenshots**
![Screen Shot 2022-04-12 at 12 15 49](https://user-images.githubusercontent.com/8966269/163007778-7ba487aa-eb22-414d-b382-85b6aa90fc56.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Browser: Safari
 - Version: 15.4

**Comment by seshrs** [comment]
Hi @sugihjamin! Sorry, I haven’t released the `no-line-numbers` feature yet 😅 

I typically release features between semesters ([SP/SU 22 milestone ETA April 30](https://github.com/eecs485staff/primer-spec/milestone/7)) — just to be extra-cautious about keeping current specs unbroken. Hope this still works with your schedule!

I’m going to leave this issue open, will check in with you again in this thread after I publish the release

**Comment by seshrs** [comment]
@sugihjamin [I just released v1.7.0](https://github.com/eecs485staff/primer-spec/releases/tag/v1.7.0%2Bss22)! This feature should work now.

I'm going to close this issue, but please follow up if you're running into issues. Thanks!

**Comment by eecs441staff** [comment]
Thanks @seshrs.  Will give it a try.

**Comment by eecs441staff** [comment]
@seshrs I'm not sure if the following is related to the new premier-spec. I don't have a `/_layouts/` folder in my GitHub Pages directory. Any ideas?

> The page build failed for the `master` branch with the following error:
> 
> The tag `seo` on line 7 in `/_layouts/spec.html` is not a recognized Liquid tag. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#unknown-tag-error.
> 
> For information on troubleshooting Jekyll see:
> 
> https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request at https://support.github.com/contact?tags=dotcom-pages&repo_id=261181978&page_build_id=336795119

**Comment by seshrs** [comment]
Sorry about that @eecs441staff! Could you please try again now? I just pushed a commit b93df3bf257082983c00d09e246b8046463de1a7 that I think should fix it.

**Comment by eecs441staff** [comment]
It's working now.  Thanks.
