### ISSUE TITLE
Enhanced Code Block First line spacing issue

### ISSUE THREAD

**Issue by jackphong** [eecs485staff/primer-spec#178]
**Describe the bug**
Currently, leading whitespace is preserved for all lines, except for the first. See the screenshots below for an example.

**Expected behavior**
Leading whitespace is preserved for the first line.

**Screenshots**
The raw text includes whitespace before the first line
![image](https://user-images.githubusercontent.com/46696737/165412925-341cd099-e2cf-441b-b330-57ddab779bd1.png)

However, this white space is not preserved, only for the first line. Line 2, which has leading whitespace, still has the correct spacing
![image](https://user-images.githubusercontent.com/46696737/165413001-305923f8-7973-407d-a923-e7882deca4f3.png)

**Additional context**
Following the guide from : https://eecs485staff.github.io/primer-spec/demo/enhanced-code-blocks.html

**Comment by seshrs** [comment]
Thanks for reporting @jackphong! The fix will be available in v1.7.0 (ETA April 30, 2022).
