### ISSUE TITLE
Sitemap: Allow external links

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#186]
@noah-weingarden and @awdeorio have a use-case where one of the tutorials associated with a project is available on an external website.

It would be nice to allow external links in the Sitemap.

**Comment by seshrs** [comment]
Here are some [currently unresolved] questions in my mind:

1. Do external links always appear at the end of a sitemap? (I think yes.)
2. Should Primer Spec sitemaps provide an option to change the order of the links? (Currently, Primer Spec uses filepath order.)
4. Should the external links appear in a visually-separate section? Or is it sufficient to just display an "external" icon next to the link?

**Comment by awdeorio** [comment]
> Do external links always appear at the end of a sitemap? (I think yes.)

That seems reasonable to me.

> Should Primer Spec sitemaps provide an option to change the order of the links? (Currently, Primer Spec uses filepath order.)

I think that would be very useful, with or without support for external links.  Take for example [EECS 280 Project 1](https://eecs280staff.github.io/p1-stats/).  The tutorials have a meaningful order which doesn't match the order they appear in the side bar.

> Should the external links appear in a visually-separate section? Or is it sufficient to just display an "external" icon next to the link?

I don't think a visually separate section is necessary.  An "external" icon would be perfect.

**Comment by noah-weingarden** [comment]
I decided to take a crack at this. 😂

**Comment by seshrs** [comment]
Implemented by @noah-weingarden in #195.

I'll close this issue after I publish a new release in a couple of weeks so that course websites (aka EECS 485 and EECS 280 😆) can start using them sooner.

**Comment by seshrs** [comment]
[v1.8.0](https://github.com/eecs485staff/primer-spec/releases/tag/v1.8.0%2Bfa22) has been published!
