### ISSUE TITLE
Bump header level styles in sidebar if needed 

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#204]
Currently, Primer Spec adds a little border for smaller headings underneath a H1. However, if the top-level heading is a H2, the style doesn’t appear. 

I think it makes sense to bump all header level styles in the sidebar so that the highest-found header level is _styled_ as a H1. 

---

Tangent: I wonder if we should also auto-ignore the first title H1 of the page from the sidebar. Or maybe it should be presented differently in the sidebar? I think I want to explore alternative header designs a bit more. 

But maybe we should provide an option to

**Comment by awdeorio** [comment]
> Tangent: I wonder if we should also auto-ignore the first title H1 of the page from the sidebar. Or maybe it should be presented differently in the sidebar? I think I want to explore alternative header designs a bit more.

I think this idea makes sense.  Typically, a document with have an H1 (the title).  All sections of the doc will be H2 and lower.  Usually, the title of a document does not appear in a table of contents.  Perhaps default to hiding the first H1, with an option to show?
