### ISSUE TITLE
Data-highlight inside callout

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#215]
**Describe the bug**
The `data-highlight` feature appears to be broken when used inside a callout.

**To Reproduce**
I couldn't get the right rendering here, so I attached an example: 
[example.md](https://github.com/eecs485staff/primer-spec/files/9708890/example.md)

**Screenshots**
<img width="935" alt="Screen Shot 2022-10-04 at 12 28 21 PM" src="https://user-images.githubusercontent.com/7503005/193874135-c8d66937-c3b1-4daf-a549-a44ce77c71b5.png">

**Comment by seshrs** [comment]
I think you placed the "data-highlight" attribute in the wrong line! It needs to be placed underneath the end of the codeblock, but inside the `<div>`. This worked for me:

````html
<div class="primer-spec-callout warning icon-warning" markdown="1">
Double-check that you didn't accidentally commit automatically generated or binary files to version control.  For example, the highlighted files are binaries.
```console
$ git ls-files
.gitignore
Makefile
main.cpp
main.exe
main.exe.dSYM/Contents/Info.plist
main.exe.dSYM/Contents/Resources/DWARF/main.exe
main_test.in
main_test.out.correct
main_test_data.tsv
p1_library.cpp
p1_library.h
stats.cpp
stats.h
stats_public_test.cpp
stats_tests.cpp
```
{: data-highlight="5-7" }
</div>
````

**Comment by awdeorio** [comment]
Welp, that's embarrassing!
