### ISSUE TITLE
Markdown tables are not rendered

### ISSUE THREAD

**Issue by santiagomed** [eecs485staff/primer-spec#220]
**Describe the bug**
[Markdown tables](https://www.markdownguide.org/extended-syntax/#tables) are not rendered when using the primer spec theme.

**To Reproduce**
1. Add a markdown table to any `.md` document
2. Serve the `.md` document using Github Pages and the primer-spec theme.
3. If you try to see your table, it will show the plain-text instead of rendering correctly

**Expected behavior**
The markdown table should be rendered as a table as shown [here](https://www.markdownguide.org/extended-syntax/#tables).

**Specific Example**
The table should render as shown [here](https://github.com/void-tech-um/react-native-workshop/tree/main/docs#components)
It fails to do so in primer-spec, as shown [here](https://voidtechmichigan.org/react-native-workshop/#components)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge v106

**Comment by seshrs** [comment]
Hi @santiagomed, thanks for using Primer Spec! I think it's pretty cool that you're using it for a non-course website. LMK if you run into issues / need support with your website's use of this theme 😃 

In this case, it looks like Jekyll's built-in markdown processor ([kramdown](https://kramdown.gettalong.org/)) didn't parse your table syntax. I'd need to see your Markdown source to be sure, but based on the HTML source, I think you just need to add an additional new line between your paragraph and your table. _(Try adding a new line between lines 237 and 238.)_

> <img width="633" alt="add a new line between lines 237 and 238" src="https://user-images.githubusercontent.com/12139762/198815684-e9b7494b-f8c0-4dfd-b8e3-b13dc5948d6d.png">

If that doesn't work, could you please either share your Markdown source, or a minimal snippet of Markdown code that reproduces the issue?

**Comment by santiagomed** [comment]
Hey! Thanks for the reply. I tried your suggestion and it worked! Thank you!
