### ISSUE TITLE
Copy button in enhanced codeblock omits whitespace

### ISSUE THREAD

**Issue by awdeorio** [eecs485staff/primer-spec#221]
**Describe the bug**
The copy feature in an enhanced code block omits whitespace.  An example of where this produces unxpected results is in the EECS 485 [Threads and Sockets in Python](https://eecs485staff.github.io/p4-mapreduce/threads-sockets.html) tutorial.

**To Reproduce**
Copy a code block containing whitespace from https://eecs485staff.github.io/p4-mapreduce/threads-sockets.html#threads and paste it into a text editor.

**Expected behavior**
Whitespace in the pasted code matches whitespace displayed in the enhanced code block.

**Comment by seshrs** [comment]
Thanks for reporting! It took me a bit to figure out what's missing: Now I realize that the copied text does not contain newlines! 😅 

Minimal repro example code block:
```python
Line 1

Line 3
```

Result after using copy button:
```
Line 1
Line 3
```

**Comment by seshrs** [comment]
I've fixed this in v1.8.3, which is live! The JS updates automatically, so you should now be able to copy the Python code from the tutorial you referenced in the issue description :)

**Comment by awdeorio** [comment]
Thanks @seshrs !
