### ISSUE TITLE
Copying an enhanced codeblock duplicates newlines

### ISSUE THREAD

**Issue by noah-weingarden** [eecs485staff/primer-spec#246]
**Describe the bug**
After clicking the visual copy button present in an enhanced codeblock and pasting the contents elsewhere, each newline in the original codeblock is duplicated.

**To Reproduce**
1. Go to https://eecs485staff.github.io/p4-mapreduce/#tests-testdata-exec-wc-reduce-py-13
2. Click on the copy button.
3. Paste into any textbox.
4. There are two newlines for each newline in the original code.

**Expected behavior**
The number of newlines in the copied code and pasted code should be the same.

**Desktop (please complete the following information):**
 - OS: Android 12/Ubuntu 22.04
 - Browser: Chrome
 - Version: 111

**Comment by seshrs** [comment]
The fix will be available in v1.9.3 (I'll release it shortly). Since it's a patch release, all specs will receive the update automatically.
