### ISSUE TITLE
Extra space on top when printing on mobile

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#42]
**Describe the bug**
When printing a spec on mobile, extra space is visible at the top. (This is likely because of the extra margin to accommodate the topbar on small browsers.)

**To Reproduce**
1. Visit a spec (say, https://eecs485staff.github.io/primer-spec/) on a mobile browser like Safari on iOS.
2. Generate a print preview by attempting to print the page.

**Expected behavior**
Content should begin at the top of the page in the preview.

**Screenshots**
Notice the extra space at the top of the preview:
<img src="https://user-images.githubusercontent.com/12139762/73627235-a4613600-4600-11ea-843e-7800098abe51.jpeg" width="300" />

Compared to this spec that is generated without Primer Spec:
<img src="https://user-images.githubusercontent.com/12139762/73627248-b17e2500-4600-11ea-85d1-cb1d761c353f.jpeg"  width="300"/>

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: iOS 13.3

**Additional context**
The potential solution will involve either adding CSS styles to prevent the margin from being printed, or to modify the JS print handlers in `NodeManager.ts` to toggle the margin before printing.

**Comment by utsavlathia** [comment]
Additionally I think this same extra space makes it so you cannot click links or copy content from the top of the browser 

Desktop (please complete the following information):
- OS: Windows 10
- Browser: Chrome

**Comment by seshrs** [comment]
> Additionally I think this same extra space makes it so you cannot click links or copy content from the top of the browser

Thanks for reporting, @utsavlathia! I think I fixed the issue you're describing as a part of #44. Can you confirm by checking out the latest build? https://preview.seshrs.ml/previews/eecs485staff/primer-spec-nightly/

**Comment by seshrs** [comment]
The issue of extra space is also related to the Topbar (like you correctly believed), but is actually caused by these lines in the CSS styling:
https://github.com/eecs485staff/primer-spec/blob/12a55ae1d9117bef1794139851880db1ebcc0717/_sass/spec/base.scss#L107-L110

The style is added when the browser window is small:
https://github.com/eecs485staff/primer-spec/blob/12a55ae1d9117bef1794139851880db1ebcc0717/src_js/NodeManager.ts#L63

One way to fix this issue is to "disable mobile mode" before printing, and then "enable mobile mode again" after printing:
https://github.com/eecs485staff/primer-spec/blob/12a55ae1d9117bef1794139851880db1ebcc0717/src_js/NodeManager.ts#L139-L186

@utsavlathia, would you like to take a stab at fixing this issue?
