### ISSUE TITLE
xcode Dark mode on sidebar as well

### ISSUE THREAD

**Issue by utsavlathia** [eecs485staff/primer-spec#46]
Would be nice and less contrasting if the dark mode also applied to the left side bar.
![image](https://user-images.githubusercontent.com/43022566/77873789-f39aa000-7218-11ea-94ea-6cacc21e1783.png)

**Comment by seshrs** [comment]
Thanks for the suggestion @utsavlathia! I *believe* the theme was designed to resemble Xcode’s “civic” theme at a time when Xcode hadn’t fully embraced dark mode. We could consider taking a second look at those theme colors. /CC @bellakiminsun

P.S: The next version of Primer Spec will include at least one full-dark theme. Check it out at https://preview.seshrs.ml/previews/eecs485staff/primer-spec-nightly. Feel free to add feedback about that too.

**Comment by utsavlathia** [comment]
Looks good, Thanks!
