### ISSUE TITLE
Persist sidebar-shown preference on large screens

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#74]
If a user has hidden the sidebar, we should keep it hidden when the page reloads. And vice-versa.

~Question: Should we persist across the site (like subthemes) or only for the page?~

Let’s persist this preference just for the page.

**Comment by bjthompson805** [comment]
I'm working on this, please assign it to me if possible.

**Comment by seshrs** [comment]
Awesome, thanks @bjthompson805! Let me know if you run into any trouble 😃 

In #72, I just added this Storage API, you'll probably find it useful:
https://github.com/eecs485staff/primer-spec/blob/9bdcb345872c19870b7ddd4a0df2fc07c8cd6a37/src_js/utils/Storage.ts#L33-L40
