### ISSUE TITLE
Unlink fork from Primer?

### ISSUE THREAD

**Issue by seshrs** [eecs485staff/primer-spec#88]
Primer Spec has diverged sufficiently enough from the original GitHub Pages Primer theme that I think it no longer makes sense to remain a “fork” of the original theme. The original theme is also very sparsely maintained — even its style dependencies aren’t up to date with the latest [@primer/css](https://github.com/primer/css) releases. 

Unlinking the fork could also help with discoverability, indicating that this repository is open to contributions from the public _without_ the intention to merge back to the original Primer theme. 

CC @awdeorio. I’ll email GitHub to unlink the fork in a couple of weeks, let me know if you have concerns about this. Thanks!

**Comment by awdeorio** [comment]
This sounds reasonable to me!

**Comment by seshrs** [comment]
Wow GitHub support is super fast, this repository is now standalone!
